name: Manual PR Creation

on:
  workflow_dispatch:
    inputs:
      from_branch:
        description: "Source branch (e.g., dev or stg)"
        required: true
        default: "dev"
      to_branch:
        description: "Target branch (e.g., stg or prod)"
        required: true
        default: "stg"

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          gh pr create --base ${{ github.event.inputs.to_branch }} --head ${{ github.event.inputs.from_branch }} --title "Auto PR: ${{ github.event.inputs.from_branch }} → ${{ github.event.inputs.to_branch }}" --body "Triggered manually from Actions tab."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
